### ISSUE TITLE
Project is being sunset

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeytrigger#19]
See [OSS lifecycle and practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)

This project has outlived its useful lifespan, and will be archived in the future.

If you are actively using `honeytrigger`, please comment on this issue with your use case.

**Comment by akeshet** [comment]
What is the basis for the assessment that this project has outlived its useful lifespan?

I am investigating tools that can automate management of honeycomb triggers, and I have not found an alternative to this.

**Comment by robbkidd** [comment]
In the last year, we have seen honeytrigger used for a total of **12** requests. (All 12 on April 20, 2022. Happy 🌍 Day!) [Triggers are supported](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs/resources/trigger) by the [Honeycomb Terraform provider](https://registry.terraform.io/providers/honeycombio/honeycombio/latest/docs) which is in higher usage by several magnitudes. We intend to shift maintenance efforts towards the Terraform provider.

@akeshet Would the Terraform provider or making API calls directly to [the triggers endpoint](https://docs.honeycomb.io/api/triggers/) meet your automation needs?

**Comment by akeshet** [comment]
I've migrated to a different terraform-based solution.
